name: release-cs


on:
  push:
    branches:
      - master

    tags:
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  release-cs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sample: ['01-in-memory']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Create package
        run: |
          cd "${{ matrix.sample }}/cs"
          make package tag=${{ github.ref_name }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.sample }}/cs/${{ matrix.sample }}-cs-sample-${{ github.ref_name }}.zip
